ALTER IGNORE TABLE jos_modules CHANGE title title VARCHAR(255);
ALTER IGNORE TABLE jos_modules ADD UNIQUE KEY (title);
--
-- Background Styles
--
INSERT INTO `jos_modules` VALUES('', 'Background Style 01', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor01</span>.</p>', 0, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor01\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 02', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor02</span>.</p>', 1, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor02\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 03', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor03</span>.</p>', 2, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor03\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 04', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-04</span>.</p>', 3, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor04\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 05', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor05</span>.</p>', 4, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor05\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 06', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor0</span>.</p>', 5, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor06\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 07', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor07</span>.</p>', 6, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor07\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 08', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor08</span>.</p>', 7, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor08\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 09', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor09</span>.</p>', 8, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor09\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 10', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor10</span>.</p>', 9, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor10\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 11', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor11</span>.</p>', 10, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor11\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 12', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor12</span>.</p>', 11, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor12\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 13', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor13</span>.</p>', 12, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor13\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 14', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor14</span>.</p>', 13, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor14\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 15', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor15</span>.</p>', 14, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor15\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 16', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor16</span>.</p>', 15, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor16\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 17', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor17</span>.</p>', 16, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor17\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 18', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor18</span>.</p>', 17, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor18\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 19', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor19</span>.</p>', 18, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor19\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Background Style 20', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgcolor20</span>.</p>', 19, 'modpreview1', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=bgcolor20\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
--
-- Heading Styles
--
INSERT INTO `jos_modules` VALUES('', 'Heading Style 01', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage01</span>.</p>', 0, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage01\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 02', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage02</span>.</p>', 1, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage02\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 03', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage03</span>.</p>', 2, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage03\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 04', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage04</span>.</p>', 3, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage04\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 05', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage05</span>.</p>', 4, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage05\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 06', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage06</span>.</p>', 5, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage06\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 07', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage07</span>.</p>', 6, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage07\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 08', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage08</span>.</p>', 7, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage08\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 09', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage09</span>.</p>', 8, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage09\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 10', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage10</span>.</p>', 9, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage10\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 11', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage11</span>.</p>', 10, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage11\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 12', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage12</span>.</p>', 11, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage12\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 13', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage13</span>.</p>', 12, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage13\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 14', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage14</span>.</p>', 13, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage14\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 15', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage15</span>.</p>', 14, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage15\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 16', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage16</span>.</p>', 15, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage16\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 17', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage17</span>.</p>', 16, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage17\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 18', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage18</span>.</p>', 17, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage18\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 19', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage19</span>.</p>', 18, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage19\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Heading Style 20', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3bgimage20</span>.</p>', 18, 'modpreview2', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3bgimage20\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
--
-- Icon Styles
--
INSERT INTO `jos_modules` VALUES('', 'Icon Style 01', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon01</span>.</p>', 0, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon01\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 02', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon02</span>.</p>', 1, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon02\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 03', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon03</span>.</p>', 2, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon03\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 04', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon04</span>.</p>', 3, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon04\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 05', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon05</span>.</p>', 4, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon05\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 06', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon06</span>.</p>', 5, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon06\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 07', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon07</span>.</p>', 6, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon07\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 08', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon08</span>.</p>', 7, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon08\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 09', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon09</span>.</p>', 8, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon09\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 10', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon10</span>.</p>', 9, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon10\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 11', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon11</span>.</p>', 10, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon11\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 12', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon12</span>.</p>', 11, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon12\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 13', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon13</span>.</p>', 12, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon13\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 14', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon14</span>.</p>', 13, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon14\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 15', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon15</span>.</p>', 14, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon15\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 16', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon16</span>.</p>', 15, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon16\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 17', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon17</span>.</p>', 16, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon17\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 18', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon18</span>.</p>', 17, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon18\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 19', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon19</span>.</p>', 18, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon19\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'Icon Style 20', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3icon20</span>.</p>', 19, 'modpreview3', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon20\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
--
-- Combo Styles
--
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 01', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon01 bgcolor01 h3bgimage11</span></p>', 0, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon01 bgcolor01 h3bgimage11\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 02', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon04 bgcolor11 h3bgimage01</span></p>', 1, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon04 bgcolor11 h3bgimage01\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 03', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon11 bgcolor02 h3bgimage12</span></p>', 2, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon11 bgcolor02 h3bgimage12\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 04', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon17 bgcolor12 h3bgimage02</span></p>', 3, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon17 bgcolor12 h3bgimage02\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 05', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon06 bgcolor03 h3bgimage13</span></p>', 4, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon06 bgcolor03 h3bgimage13\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 06', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon03 bgcolor13 h3bgimage03</span></p>', 5, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon03 bgcolor13 h3bgimage03\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 07', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon09 bgcolor04 h3bgimage14</span></p>', 6, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon09 bgcolor04 h3bgimage14\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 08', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon20 bgcolor14 h3bgimage04</span></p>', 7, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon20 bgcolor14 h3bgimage04\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 09', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon15 bgcolor05 h3bgimage15</span></p>', 8, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon15 bgcolor05 h3bgimage15\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 10', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon13 bgcolor15 h3bgimage05</span></p>', 9, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon13 bgcolor15 h3bgimage05\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 11', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon12 bgcolor06 h3bgimage16</span></p>', 10, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon12 bgcolor06 h3bgimage16\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 12', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon05 bgcolor16 h3bgimage06</span></p>', 11, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon05 bgcolor16 h3bgimage06\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 13', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon10 bgcolor07 h3bgimage17</span></p>', 12, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon10 bgcolor07 h3bgimage17\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 14', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon07 bgcolor17 h3bgimage07</span></p>', 13, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon07 bgcolor17 h3bgimage07\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 15', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon08 bgcolor08 h3bgimage18</span></p>', 14, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon08 bgcolor08 h3bgimage18\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 16', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon12 bgcolor18 h3bgimage08</span></p>', 15, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon12 bgcolor18 h3bgimage08\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 17', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon14 bgcolor09 h3bgimage19</span></p>', 16, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon14 bgcolor09 h3bgimage19\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 18', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon02 bgcolor19 h3bgimage09</span></p>', 17, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon02 bgcolor19 h3bgimage09\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 19', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon19 bgcolor10 h3bgimage20</span></p>', 18, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon19 bgcolor10 h3bgimage20\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
INSERT INTO `jos_modules` VALUES('', 'ModFX Combo 20', '<p>This module uses a combination of the following module suffixes: <span class="class-name">h3icon16 bgcolor20 h3bgimage10</span></p>', 19, 'modpreview4', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 0, 1, 'moduleclass_sfx=h3icon16 bgcolor20 h3bgimage10\n\n', 0, 0, '') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO `jos_modules_menu` VALUES(LAST_INSERT_ID(), '0') ON DUPLICATE KEY UPDATE menuid=menuid;
ALTER IGNORE TABLE jos_modules DROP INDEX title;
ALTER IGNORE TABLE jos_modules CHANGE title title TEXT;