INSERT INTO `jos_modules_menu` VALUES(43, 0);
INSERT INTO `jos_modules_menu` VALUES(44, 0);
INSERT INTO `jos_modules_menu` VALUES(45, 0);
INSERT INTO `jos_modules_menu` VALUES(46, 0);
INSERT INTO `jos_modules_menu` VALUES(47, 0);
INSERT INTO `jos_modules_menu` VALUES(48, 0);
INSERT INTO `jos_modules_menu` VALUES(49, 0);
INSERT INTO `jos_modules_menu` VALUES(50, 0);
INSERT INTO `jos_modules_menu` VALUES(51, 0);
INSERT INTO `jos_modules_menu` VALUES(52, 0);
INSERT INTO `jos_modules_menu` VALUES(53, 0);
INSERT INTO `jos_modules_menu` VALUES(54, 0);
INSERT INTO `jos_modules_menu` VALUES(55, 0);
INSERT INTO `jos_modules_menu` VALUES(56, 0);
INSERT INTO `jos_modules_menu` VALUES(57, 0);
INSERT INTO `jos_modules_menu` VALUES(58, 0);
INSERT INTO `jos_modules_menu` VALUES(59, 0);
INSERT INTO `jos_modules_menu` VALUES(60, 0);
INSERT INTO `jos_modules_menu` VALUES(61, 0);
INSERT INTO `jos_modules_menu` VALUES(62, 0);
INSERT INTO `jos_modules_menu` VALUES(63, 0);
INSERT INTO `jos_modules_menu` VALUES(64, 0);
INSERT INTO `jos_modules_menu` VALUES(65, 0);
INSERT INTO `jos_modules_menu` VALUES(66, 0);
INSERT INTO `jos_modules_menu` VALUES(67, 0);
INSERT INTO `jos_modules_menu` VALUES(68, 0);
INSERT INTO `jos_modules_menu` VALUES(69, 0);
INSERT INTO `jos_modules_menu` VALUES(70, 0);
INSERT INTO `jos_modules_menu` VALUES(71, 0);
INSERT INTO `jos_modules_menu` VALUES(72, 0);
INSERT INTO `jos_modules_menu` VALUES(73, 0);
INSERT INTO `jos_modules_menu` VALUES(74, 0);
INSERT INTO `jos_modules_menu` VALUES(75, 0);
INSERT INTO `jos_modules_menu` VALUES(76, 0);
INSERT INTO `jos_modules_menu` VALUES(77, 0);
INSERT INTO `jos_modules_menu` VALUES(78, 0);
INSERT INTO `jos_modules_menu` VALUES(79, 0);
INSERT INTO `jos_modules_menu` VALUES(80, 0);
INSERT INTO `jos_modules_menu` VALUES(81, 0);
INSERT INTO `jos_modules_menu` VALUES(82, 0);
INSERT INTO `jos_modules_menu` VALUES(83, 0);
INSERT INTO `jos_modules_menu` VALUES(84, 0);
INSERT INTO `jos_modules_menu` VALUES(85, 0);
INSERT INTO `jos_modules_menu` VALUES(86, 0);
INSERT INTO `jos_modules_menu` VALUES(87, 0);
INSERT INTO `jos_modules_menu` VALUES(88, 0);
INSERT INTO `jos_modules_menu` VALUES(89, 0);
INSERT INTO `jos_modules_menu` VALUES(90, 0);
INSERT INTO `jos_modules_menu` VALUES(91, 0);
INSERT INTO `jos_modules_menu` VALUES(92, 0);
INSERT INTO `jos_modules_menu` VALUES(93, 0);
INSERT INTO `jos_modules_menu` VALUES(94, 0);
INSERT INTO `jos_modules_menu` VALUES(95, 0);
INSERT INTO `jos_modules_menu` VALUES(96, 0);
INSERT INTO `jos_modules_menu` VALUES(97, 0);
INSERT INTO `jos_modules_menu` VALUES(98, 0);
INSERT INTO `jos_modules_menu` VALUES(99, 0);
INSERT INTO `jos_modules_menu` VALUES(100, 0);

INSERT INTO `jos_modules` VALUES('', 'Background Style 1', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-01</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-01\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 2', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-02</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-02\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 3', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-03</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-03\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 4', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-04</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-04\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 5', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-05</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-05\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 6', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-06</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-06\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 7', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-07</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-07\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 8', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-08</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-08\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 9', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-09</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-09\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 10', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-10</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-10\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 11', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-11</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-11\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 12', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-12</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-12\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 13', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-13</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-13\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 14', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-14</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-14\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 15', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-15</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-15\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 16', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-16</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-16\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 17', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-17</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-17\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 18', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-18</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-18\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 19', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-19</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-19\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Background Style 20', '<p>This is how the module background will look if you set the suffix to <span class="class-name">bgstyle-20</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=bgstyle-20\n\n', 0, 0, '');

INSERT INTO `jos_modules` VALUES('', 'Heading Style 1', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-01</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-01\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 2', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-02</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-02\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 3', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-03</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-03\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 4', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-04</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-04\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 5', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-05</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-05\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 6', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-06</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-06\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 7', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-07</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-07\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 8', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-08</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-08\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 9', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-09</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-09\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 10', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-10</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-10\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 11', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-11</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-11\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 12', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-12</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-12\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 13', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-13</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-13\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 14', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-14</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-14\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 15', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-15</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-15\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 16', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-16</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-16\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 17', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-17</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-17\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 18', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-18</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-18\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 19', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-19</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-19\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 20', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-20</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-20\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 21', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-21</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-21\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 22', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-22</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-22\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 23', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-23</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-23\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 24', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-24</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-24\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Heading Style 25', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">h3style-25</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=h3style-25\n\n', 0, 0, '');

INSERT INTO `jos_modules` VALUES('', 'Icon Style 1', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">iconstyle-01</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=iconstyle-01\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Icon Style 2', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">iconstyle-02</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=iconstyle-02\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Icon Style 3', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">iconstyle-03</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=iconstyle-03\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Icon Style 4', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">iconstyle-04</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=iconstyle-04\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Icon Style 5', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">iconstyle-05</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=iconstyle-05\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Icon Style 6', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">iconstyle-06</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=iconstyle-06\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Icon Style 7', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">iconstyle-07</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=iconstyle-07\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Icon Style 8', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">iconstyle-08</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=iconstyle-08\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Icon Style 9', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">iconstyle-09</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=iconstyle-09\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Icon Style 10', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">iconstyle-10</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=iconstyle-10\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Icon Style 11', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">iconstyle-11</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=iconstyle-11\n\n', 0, 0, '');
INSERT INTO `jos_modules` VALUES('', 'Icon Style 12', '<p>This is how the module heading will look if you set the suffix to <span class="class-name">iconstyle-12</span>.</p>', '', 'left', 0, '0000-00-00 00:00:00', 1, 'mod_custom', 0, 2, 1, 'moduleclass_sfx=iconstyle-12\n\n', 0, 0, '');
